from faker import Faker
import csv
import random

# Initialize Faker
fake = Faker()

PROGRAM_MAPPING = {
    'STP': 'Scientist Training Programme',
    'HSST': 'Higher Specialist Scientist Training',
    'CDSP': 'Clinical Data Science Programme',
    'HSSTP': 'Higher Specialist Scientist Training Programme',
    'PTP': 'Practitioner Training Programme',
    'ETP': 'Echocardiography Training Programme',
}

SPECIALISMS = [
    "Microbiology",
    "Virology",
    "Clinical Immunology",
    "Imaging (Non-Ionising Radiation)",
    "Molecular Pathology of Infection",
    "Vascular Science",
    "Clinical Pharmaceutical Science",
    "Clinical Microbiology",
    "Cytopathology",
    "Critical Care Science",
    "Neurophysiology",
    "Molecular Pathology of Acquired Disease",
    "Ophthalmic & Vision Sciences",
    "Audiology",
    "Cancer Genomics",
    "Bioinformatics - Genomics",
    "Clinical Bioinformatics - Physics and Engineering Informatics",
    "Clinical Bioinformatics - Physical Sciences",
    "Urological Science",
    "Clinical Measurement & Development",
    "Medical Physics - Unspecified",
    "Medical Device Risk Management & Governance",
    "Imaging Physics",
    "Clinical Biomedical Engineering",
    "Nuclear Medicine",
    "Gastrointestinal Physiology",
    "Echocardiography PG Cert",
    "Diagnostic Imaging Science",
    "Cardiac Science - Echo",
    "Reproductive Science - Embryology",
    "Radiation Safety Physics",
    "Radiotherapy Physics",
    "Reconstructive Science",
    "Rehabilitation Engineering",
    "Reproductive Science - Andrology",
    "Genetics",
    "Reproductive Science (HSST)",
    "Respiratory & Sleep Physiology",
    "Genomic Counselling",
    "Genomics",
    "Haematology",
    "Respiratory & Sleep Sciences",
    "Clinical Biochemistry",
    "Clinical Bioinformatics - Genomics",
    "Imaging (Ionising Radiation)",
    "Transfusion Science",
    "Haematology & Transfusion Science",
    "Urodynamic Science",
    "Clinical Bioinformatics - Health Informatics",
]

REGIONS = [
    "East of England",
    "London",
    "Midlands",
    "NHS Northern Ireland",
    "NHS Scotland",
    "NHS Wales",
    "North East & Yorkshire",
    "North West",
    "Northern Ireland",
    "South East",
    "South West",
]

ICB = [
    "NHS Bedforshire, Luton and Milton Keynes",
    "NHS Hertfordshire and West Essex",
    "NHS Mid and South Essex",
    "NHS Norfolk and Waveney",
    "NHS Suffolk and North East Essex",
    "NHS North West London",
    "NHS South East London",
    "NHS North Central London",
    "NHS North East London",
    "NHS South West London",
    "NHS Northamptonshire",
    "NHS Nottingham and Nottinghamshire",
    "NHS Shropshire, Telford and Wrekin",
    "NHS Derby and Derbyshire",
    "NHS Staffordhsire and Stoke-on-Trent",
    "NHS Birmingham and Solihull",
    "NHS Humber and North Yorkshire",
    "NHS North East and North Cumbria",
    "NHS South Yorkshire",
    "NHS West Yorkshire",
    "NHS Greater Manchester",
    "NHS Lancashire and South Cumbria",
    "NHS Surrey Heartlands",
    "NHS Sussex",
    "NHS Kent and Medway",
    "NHS Hampshire and Isle of Wight",
    "NHS Frimley",
    "NHS Buckinghamshire, Oxfordshire and Berkshire West",
    "NHS Cornwall and The Isles of Scilly",
    "NHS Bristol, North Somerset and South Gloucestershire",
    "NHS Devon",
    "NHS Dorset",
    "NHS Gloucestershire",
    "NHS Somerset",
    "NHS Cambridgeshire and Peterborough",
    "NHS Stafforsdshire and Stoke-on-Trent",
    "NHS Black Country",
    "NHS Coventry and Warwickshire",
    "NHS Herefordshire and Worcestershire",
    "NHS Leicester, Leicestershire and Rutland",
    "NHS Cheshire and Merseyside",
    "NHS Lincolnshire",
    "NHS Bath and North East Somerset, Swindon and Wiltshire",
]

TRUST = [
    "Colchester University NHS Foundation Trust",
    "Salford Royal NHS Foundation Trust",
    "Sandwell and West Birmingham Hospitals NHS Trust",
    "University Hospitals Birmingham NHS Foundation Trust",
    "Cambridge University Hospitals NHS Foundation Trust",
    "Northampton General Hospital NHS Trust",
    "Royal Devon and Exeter NHS Foundation Trust",
    "Royal Surrey NHS Foundation Trust",
    "Great Ormond Street Hospital for Children NHS Foundation Trust",
    "Mid Yorkshire Hospitals NHS Trust",
    "Royal Cornwall Hospitals NHS Trust",
    "London North Consortium",
    "Maidstone and Tunbridge Wells NHS Trust",
    "Guy's and St Thomas' NHS Foundation Trust",
    "Hampshire Hospitals NHS Foundation Trust",
    "Poole Hospital NHS Foundation Trust",
    "East and North Hertfordshire NHS Trust",
    "Stockport NHS Foundation Trust",
    "Sussex Community NHS Foundation Trust",
    "Barts Health NHS Trust",
    "St George's University Hospitals NHS Foundation Trust",
    "St Helens and Knowsley Teaching Hospitals NHS Trust",
    "Frimley Health NHS Foundation Trust",
    "King's College Hospital NHS Foundation Trust",
    "University Hospitals Plymouth NHS Trust",
    "Kettering General Hospital NHS Foundation Trust",
    "London North West University Healthcare NHS Trust",
    "Nottingham University Hospitals NHS Trust",
    "Oxford University Hospitals NHS Foundation Trust",
    "Peterborough & Stamford NHS Foundation Trust",
    "Somerset NHS Foundation Trust",
    "The Royal Marsden NHS Foundation Trust",
    "South Tees Hospitals NHS Foundation Trust",
    "Hull University Teaching Hospitals NHS Trust",
    "University Hospitals Coventry & Warwickshire NHS Trust",
    "South London Consortium",
    "Salisbury NHS Foundation Trust",
    "University Hospitals Bristol and Weston NHS Foundation Trust",
    "Royal Free London NHS Foundation Trust",
    "Royal United Hospitals Bath NHS Foundation Trust",
    "University Hospital Southampton NHS Foundation Trust",
    "Derby Hospitals NHS Foundation Trust",
    "Burton Hospitals NHS Foundation Trust",
    "United Lincolnshire Hospitals NHS Trust",
    "Mid Cheshire Hospitals NHS Foundation Trust",
    "Birmingham Children's Hospital NHS Foundation Trust",
    "Belfast Health & Social Care Trust",
    "Cwm Taf Morgannwg University Health Board",
    "Royal Brompton & Harefield NHS Foundation Trust",
    "Cardiff and Vale University Health Board",
    "Leeds Teaching Hospitals NHS Trust",
    "University Hospitals of North Midlands NHS Trust",
    "Sheffield Children's NHS Foundation Trust",
    "County Durham and Darlington NHS Foundation Trust",
    "Gateshead Health NHS Foundation Trust",
    "Bradford Teaching Hospitals NHS Foundation Trust",
    "Central Manchester University Hospitals NHS Foundation Trust",
    "Blackpool Teaching Hospitals NHS Foundation Trust",
    "Bolton NHS Foundation Trust",
    "East Sussex Healthcare NHS Trust",
    "Kingston Hospital NHS Foundation Trust",
    "Brighton and Sussex University Hospitals NHS Trust",
    "University Hospital of South Manchester NHS Foundation Trust",
    "Ashford and St Peter's Hospitals NHS Foundation Trust",
    "Berkshire Healthcare NHS Foundation Trust",
    "Royal Berkshire NHS Foundation Trust",
    "Gloucestershire Hospitals NHS Foundation Trust",
    "Portsmouth Hospitals NHS Trust",
    "Queen Victoria Hospital NHS Foundation Trust",
    "Imperial College Healthcare NHS Trust",
    "Royal Devon and Exeter NHS Foundation TrustRoyal Cornwall Hospitals NHS Trust",
    "Sheffield Teaching Hospitals NHS Foundation Trust",
]

HOSPITAL = [
    "St. Mary's Pharmaceutical Unit, Cardiff",
    "St Mary’s Hospital",
    "Royal Blackburn Hospital",
    "Epsom General Hospital",
    "Royal Alexandra Hospital",
    "Velindre Cancer Centre",
    "Blackpool Teaching Hospitals NHS Foundation Trust",
    "Central Manchester University Hospitals NHS Foundation Trust",
    "George Eliot Hospital",
    "Welsh Blood Service",
    "Royal Brompton Hospital",
    "North Devon District Hospital,",
    "Southmead Hospital",
    "Mater Hospital",
    "NHS England - London",
    "St Luke's Hopital",
    "Bronglais General Hospital",
    "CARE Fertility Birmingham",
    "TriTech Institute",
    "Velindre Hospital",
    "Health Service Laboratories",
    "Wales Fertility Institute Neath and Cardiff",
    "Royal Hampshire County Hospital",
    "Poole Hospital",
    "Bryn y Neuadd Hospital",
    "Camelia Botnar Laboratories",
    "Good Hope Hospital",
    "St George's Hospital (Lon North Consortium)",
    "Bristol Heart Institute",
    "Bristol Royal Hospital For Children",
    "Gloucester Royal Hospital",
    "Airedale General Hospital",
    "CARE Fertility Chester",
    "Chailey Clinical Services",
    "Christie Hospital, The",
    "Manchester Royal Infirmary",
    "Royal Bolton Hospital",
    "Chime Social Enterprise",
    "Queen Elizabeth University Hospital, Glasgow",
    "Royal National ENT Hospital",
    "Bristol Genetics Laboratory",
    "Charing Cross Hospital (Lon North Consortium)",
    "Barking, Havering and Redbridge University Hospitals NHS Trust",
    "St. Helier Hospital",
    "Alder Hey Children's Hospital",
    "Barnet General Hospital",
    "Queens Hospital, Romford",
    "Kingston Hospital & St Mary's Hospital",
    "Royal Oldham Hospital",
    "Moorfields Eye Hospital",
    "Cumberland Infirmary",
    "The Centre for Reproductive and Genetic Health",
    "Great Western Hospital",
    "Cheltenham General Hospital",
    "Worcestershire Royal Hospital",
    "CRGH London",
    "Worcester Acute Hospitals NHS Trust",
    "Homerton University Hospital",
    "University Hospitals Coventry & Warwickshire NHS Trust (WM Consortium)",
    "Basingstoke and North Hampshire Hospital",
    "Pilgrim Hospital",
    "Royal Preston Hospital",
    "The National Hospital for Neurology and Neurosurgery",
    "Wessex Regional Genetics Laboratory",
    "The Grange University Hospital",
    "Frenchay Hospital",
    "Mount Vernon Cancer Centre (Lon North Consortium)",
    "Conquest Hospital, East Sussex",
    "Royal Stoke University Hospital",
    "University Hospital Coventry",
    "University Hospitals Coventry & Warwickshire NHS Trust",
    "Walsall Manor Hospital",
    "Royal Devon and Exeter Hospital",
    "UKHSA - Birmingham",
    "University Hospital Monklands",
    "Cedar Healthcare Technology Research Centre",
    "Derriford Hospital",
    "Salisbury District Hospital",
    "Castle Hill Hospital",
    "Bourn Hall Clinic Norwich",
    "Cambridge IVF",
    "Singleton Hospital",
    "Northern Ireland Cancer Centre",
    "Queen Victoria Hospital",
    "Doncaster Royal Infirmary",
    "Liverpool Women's Hospital",
    "Milton Keynes Hospital",
    "Bristol Haematology And Oncology Centre",
    "Forster Green Hospital",
    "Hull IVF Unit, The",
    "Hull Royal Infirmary",
    "Chase Farm Hospital",
    "Pinderfield Hospital",
    "Chester and Wirral Microbiology Service",
    "Sandwell and West Birmingham Hospitals NHS Trust",
    "Gartnavel General Hospital",
    "Gennet City Fertility",
    "Southampton General Hospital",
    "University Hospital Southampton NHS Foundation Trust",
    "Portsmouth Hospitals NHS Trust",
    "Queen Alexandra Hospital",
    "Royal Bournemouth Hospital",
    "West Midlands Regional Genomics Hub",
    "CARE Fertility Tunbridge Wells",
    "Nottingham University Hospitals NHS Trust",
    "Burnley General Teaching Hospital",
    "Leeds General Infirmary",
    "Seacroft Hospital",
    "Aintree University Hospital",
    "Leeds Teaching Hospitals NHS Trust",
    "Leeds Centre for Reproductive Medicine",
    "Dorset County Hospital",
    "Queen's Hospital, Romford",
    "Bristol Eye Hospital",
    "St Bartholomew's Hospital",
    "Musgrove Park Hospital,",
    "UKHSA Colindale",
    "Leicester General Hospital",
    "Melchett Road Aseptics Unit",
    "Royal United Hospital",
    "St James's University Hospital",
    "University Hospital Ayr",
    "North Middlesex University Hospital",
    "Royal Cornwall Hospital",
    "Bradford Royal Infirmary",
    "King Edward VII Hospital",
    "The Priory Hospital (BMI)",
    "Trafford General Hospital",
    "CARE Fertility Sheffield",
    "Glasgow Royal Infirmary",
    "University Hospital of North Durham",
    "St. Michael's Hospital",
    "CARE Fertility Bath",
    "Churchill Hospital",
    "John Radcliffe Hospital",
    "Wexham Park Hospital",
    "Dumfries & Galloway Royal Infirmary",
    "Princess Royal Hospital, The",
    "Wishaw General Hospital",
    "Birmingham Women's Hospital",
    "Nuffield Health Woking Hospital",
    "Berkshire Healthcare NHS Foundation Trust",
    "Leighton Hospital",
    "Vicarage Lane Health Centre",
    "West Midlands Rehabilitation Centre Birmingham",
    "Sheffield Teaching Hospitals NHS Foundation Trust",
    "Children's Hospital Sheffield, The",
    "Burton Hospitals NHS Foundation Trust",
    "Birmingham Heartlands Hospital",
    "Solihull Hospital",
    "Macclesfield District General Hospital",
    "Forth Valley Royal Hospital",
    "Liverpool Heart and Chest Hospital",
    "Birmingham Children's Hospital",
    "Stepping Hill Hospital",
    "Royal Liverpool University Hospital",
    "Salford Royal Hospital",
    "St Helens Hospital",
    "Whiston Hospital",
    "York Hospital",
    "Northern General Hospital",
    "Radiation Protection Services (RRPPS)",
    "Royal Hallamshire Hospital",
    "Princess of Wales Hospital",
    "Shropshire and Mid Wales Fertility Centre",
    "West Middlesex Hospital",
    "Bristol Royal Infirmary",
    "CRGWW Plymouth",
    "Neath Port Talbot Hospital",
    "Newcastle Centre for Life",
    "Sandwell and West Birmingham Hospitals NHS Trust (Consortium)",
    "Jessop Wing",
    "IVI London",
    "Hammersmith Hospital",
    "Glangwili General Hospital",
    "St Thomas' Hospital",
    "Guy's & St Thomas' NHS Foundation Trust",
    "Walton Centre, The",
    "Royal London Hospital",
    "Charing Cross Hospital",
    "NHS Blood and Transplant - Newcastle",
    "Abertawe Bro Morgannwg Univ Health Board",
    "Guy's Hospital",
    "Hereford County Hospital",
    "Morriston Hospital",
    "Royal Berkshire Hospital",
    "Queen Elizabeth Hospital, King's Lynn",
    "CARE Fertility Tamworth",
    "Sunderland Royal Hospital",
    "St Margaret's Hospital, Epping",
    "Withybush General Hospital",
    "North West Genomic Laboratory Hub",
    "Wirral University Teaching Hospital NHS Foundation Trust",
    "King's Fertility",
    "Sheffield Diagnostic",
    "Bristol Centre for Reproductive Medicine",
    "NHS Blood and Transplant - Birmingham",
    "NHS Blood and Transplant - Tooting",
    "Wythenshawe Hospital",
    "NHS Blood and Transplant - Bristol",
    "NHS Blood and Transplant - Liverpool",
    "NHS Blood and Transplant - Sheffield",
    "Altnagelvin Hospital",
    "James Cook University Hospital",
    "Electronic Assistive Technology Service (Lincoln)",
    "Warwick Hospital",
    "Birmingham (Publich Health Labs)",
    "Belfast City Hospital",
    "NHS Golden Jubilee",
    "Northwick Park Hospital",
    "University Hospital of South Manchester NHS Foundation Trust",
    "Great Ormond Street Hospital",
    "Glan Clwyd Hospital",
    "Aberdeen Royal Infirmary",
    "The Evewell Clinic",
    "Nuffield Orthopaedic Centre",
    "NHS Blood and Transplant - Colindale",
    "Bishop Auckland Hospital",
    "NHS Blood and Transplant - Barnsley",
    "Hevitree Hospital",
    "Russells Hall Hospital",
    "University Hospital Llandough",
    "Betsi Cadwaladr University Health Board",
    "West Suffolk Hospital",
    "University Hospital Aintree",
    "Wrexham Maelor Hospital",
    "RJAH Orthopaedic Hospital",
    "CARE Fertility Manchester",
    "New Cross Hospital",
    "Centre for Life",
    "Rotherham General Hospital",
    "St. Bartholomew's Hospital",
    "Royal Victoria Infirmary",
    "Royal Free Hospital",
    "Royal Lancaster Infirmary",
    "North Scotland Clinical Genetics Service",
    "Broomfield Hospital",
    "Countess of Chester Hospital",
    "Withington Community Hospital",
    "Princess Alexandra Hospital NHS Trust, The",
    "Yorkhill Hospital",
    "Chapel Allerton Hospital",
    "Prince Charles Hospital",
    "Ysbyty Gwynedd",
    "Cardiff and Vale University Health Board",
    "Princess of Wales Hospital, Glamorgan",
    "CARE Fertility Northampton",
    "Prince Philip Hospital, Llanelli",
    "Royal Wolverhampton Hospital",
    "Royal Marsden Hospital, The",
    "New Victoria Hospital",
    "Raigmore Hospital",
    "Ninewells Hospital",
    "King's College Hospital",
    "Southern General Hospital",
    "Arrowe Park Hospital",
    "CARE Fertility Woking",
    "Posture and Mobility Centre, Treforest",
    "Princess Anne Hospital, Southampton",
    "Royal Gwent Hospital",
    "NHS Blood and Transplant - Leeds",
    "Royal Glamorgan Hospital",
    "Ysbyty Wrexham Maelor",
    "University Hospital of Wales",
    "University College Hospital",
    "UKHSA - Site Unknown",
    "Moor House, Leeds",
    "Royal Shrewsbury Hospital",
    "City General Hospital",
    "Queen Elizabeth Hospital Birmingham",
    "University Hospital of North Staffordshire NHS Trust",
    "Western General Hospital",
    "CARE Fertility Nottingham",
    "Queen Elizabeth Hospital Gateshead",
    "Sandwell General Hospital",
    "City Hospital (SWBH)",
    "Queen Mary's Hospital",
    "KCH/GST/Marsden/UCL",
    "Queen's Hospital",
    "Royal Victoria Hospital",
    "London Women's Clinic",
    "St George's Hospital",
]

OUTCOMES = [
    "Pass",
    "Fail",
    ""
]

HEI = [
    "Cardiff University",
    "University of Birmingham",
    "University College London",
    "University of Nottingham",
    "University of Southampton",
    "University of Warwick",
    "Imperial College London",
    "University of Liverpool",
    "University of Manchester",
    "Queen's University Belfast",
    "University of Leeds",
    "University of Cambridge",
    "University of Sheffield",
    "University of Oxford",
    "Newcastle University",
    "King's College London",
]

CASE_MANAGERS = [
    "Phillip Willis",
    "Francisco Sharp",
    "Jason Taylor",
    "Dr. Shane Wilson",
    "Tracy Gonzalez",
    "Renee Harris",
    "Christy Massey",
    "Karen Forbes",
    "Carrie Mcconnell",
]
# Function to generate a row of fake data similar to the Excel structure
def generate_fake_row():
    program_index = fake.random_int(min=0, max=len(PROGRAM_MAPPING) - 1)
    return {
        "id": fake.unique.random_int(min=100000, max=999999),
        "nshsc-id": fake.unique.random_int(min=100000, max=999999),
        "trainee-url": "https://torchbox.github.io/NSHCS-TMS/templates/details-view.html",
        "surname": fake.last_name(),
        "forename": fake.first_name(),
        "dob": fake.date_of_birth(minimum_age=18, maximum_age=60).strftime('%Y-%m-%d'),
        "email": fake.email(),
        "gender": random.choice(["Male", "Female", "Other", "Prefer not to say"]),
        "ethnicity": random.choice(["White", "Asian", "Black", "Other", "Prefer not to say"]),
        "disability": random.choice(["Y", "N"]),
        "religion": random.choice(["Christian", "Muslim", "Hindu", "Sikh", "Jewish", "Buddhist", "Other", "Prefer not to say"]),
        "programme": PROGRAM_MAPPING[list(PROGRAM_MAPPING.keys())[program_index]],
        "programme-abbr": list(PROGRAM_MAPPING.keys())[program_index],
        "specialism": SPECIALISMS[fake.random_int(min=0, max=len(SPECIALISMS) - 1)],
        "progress": fake.random_int(1, 100),
        "cohort": fake.random_int(min=2015, max=2021),
        "region": REGIONS[fake.random_int(min=0, max=len(REGIONS) - 1)],
        "icb": ICB[fake.random_int(min=0, max=len(ICB) - 1)],
        "trust": TRUST[fake.random_int(min=0, max=len(TRUST) - 1)],
        "hospital": HOSPITAL[fake.random_int(min=0, max=len(HOSPITAL) - 1)],
        "supported": random.choice(["Y", "N"]),
        "employer": fake.company(),
        "training site": HOSPITAL[fake.random_int(min=0, max=len(HOSPITAL) - 1)],
        "case manager": CASE_MANAGERS[fake.random_int(min=0, max=len(CASE_MANAGERS) - 1)],
        "case status": random.choice(["Open", "Close", None]),
        "case issue/tag/category": random.choice(["category 1", "category 2", "category 3", "category 4"]),
        "outcome": OUTCOMES[fake.random_int(min=0, max=len(OUTCOMES) - 1)],
        "review 1": fake.random_int(min=1, max=3) if fake.boolean() else None,
        "review 2": fake.random_int(min=1, max=3) if fake.boolean() else None,
        "review 3": fake.random_int(min=1, max=3) if fake.boolean() else None,
        "review 4": fake.random_int(min=1, max=3) if fake.boolean() else None,
        "mrp-test": fake.random_int(min=1, max=3),
        "progress-url": "https://torchbox.github.io/NSHCS-TMS/templates/progress-view.html",
        "hei": HEI[fake.random_int(min=0, max=len(HEI) - 1)],
        "status": random.choice(['Active - FT', 'Active - PT', 'Inactive', 'Inactive - Failed', 'Inactive - Passed', "Inactive - Withdrawn"]),

    }

# Number of records to generate
num_records = 100

# File path for the CSV
csv_file_path = 'fake_nshcs_data.csv'

def main():
    # Writing the fake data to a CSV file
    with open(csv_file_path, mode='w', newline='', encoding='utf-8') as file:
        writer = csv.DictWriter(file, fieldnames=generate_fake_row().keys())
        writer.writeheader()
        for _ in range(num_records):
            writer.writerow(generate_fake_row())

    print(f"CSV file created at {csv_file_path}")

if __name__ == "__main__":

    main()